---
title: "STA457 Final Project Rmd"
author: "Liang Chen"
date: "07/04/2021"
output: pdf_document
#fig_width: 4 
#fig_height: 4 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

## plotting and transformation
```{r, echo=FALSE,figures-side, fig.show="hold", out.width="50%",main="a" , message=FALSE}
#load the original data of co2 concentration collected  at Mauna Loa Observatory, Haiwaii
co2s=read.table("/Users/liangchen/Downloads/STA457/Final Project/daily_flask_co2_mlo.csv",header =FALSE,sep =",",
                skip =69,stringsAsFactors =FALSE,
                col.names =c("day","time","junk1",
                             "junk2","Nflasks","quality","co2"))

# change the format of cod time stampe in cvs file
co2s$date=strptime(paste(co2s$day, co2s$time),
                   format ="%Y-%m-%d %H:%M",
                   tz ="UTC")

# remove low-quality measurements
co2s=co2s[co2s$quality==0, ]

# use recent 5 years' data (from 2016/01/25 to 2021/01/26)
co2_new = co2s$co2[co2s$date>ISOdate(2016,01,25,tz ="UTC")]
# check sample size
length(co2_new)

# detrend first since there exist significant upward trend
dlco2s = diff(log(co2_new))

# there exist seasonal trend, and data is collected weekly, deal with data's seasonal trend
ddlco2s=diff(dlco2s, 52)

#plot the three time series
par(mfrow=c(1,1))
plot(ts(co2s$co2), xlab="Time:weekly (year 1960 to 2021)", ylab="CO2 Concentration: ppm")
plot(ts(co2_new), xlab="Time:weekly (year 2016 to 2021)", ylab="CO2 Concentration: ppm")

#plot(ts(dlco2s), main="diff(log(co2)) in recent 10 years",xlab="Time:weekly", ylab="log(Concentration): log(ppm)")
plot(ts(ddlco2s),xlab="Time:weekly (year 2016 to 2021)", ylab="diff(diff(log(CO2)), 52): log(ppm)")

```

## identifying the dependence orders 
```{r pressure, echo=FALSE,fig.height = 3, fig.width = 3}
library(astsa)
# generate ACF and PACF for ddlco2s dataset
acf2(ddlco2s, 150)
# seasonal component: D=1, P=1, Q = 1
# non-seasonal compoment: d=1, p = 1, q = 1 or 0
```



## parameter estimation,  diagnostics, model choice
```{r pressure1, echo=FALSE,,fig.height = 4, fig.width = 8}
# generate log(co2)
lco2 = log(co2_new)
# fit first SARIMA model for log(co2)
model1=sarima(lco2, 1,1,1,1,1,1,52) 
# fit second SARIMA model for log(co2)
model2=sarima(lco2, 1,1,0,1,1,1,52) 
model1
model2
```

## forecast
The prediction plot and the values are:\
```{r pressure2, echo=FALSE,fig.height = 3, fig.width = 8}
# do forecasting of next ten weeks log(co2)
pred1=sarima.for(lco2,10, 1,1,0,1,1,1,52) 
# upper bound of prediction
U = pred1$pred+qnorm(.975)*pred1$se
# lower bound of prediction
L= pred1$pred-qnorm(.975)*pred1$se
cbind(L,U)
pred1$pred
```


## identify the dominant frequencies 

```{r pressure3, echo=FALSE,fig.height = 3, fig.width = 3}
# generate preiodogram of co2
co2_new.per = mvspec(co2_new, log = "no")
# reordering spectrum by decreasing order
p=co2_new.per$details[order(co2_new.per$details[,3],decreasing=TRUE),]
# get the first three dominant ones
p[1:3,3]
# upper bound of 95% ci of spectrum 
upper=2*p[1:3,3]/qchisq(.025 ,2)
# lower bound of 95% ci of spectrum
lower=2*p[1:3,3]/qchisq(.975 ,2)
upper
lower
```


## discussion

